version: '3.8'

services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: swagger-editor
    ports:
      - "8080:8080"
    volumes:
      - ./api.yaml:/tmp/api.yaml
    environment:
      SWAGGER_FILE: /tmp/api.yaml

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /api.yaml
    volumes:
      - ./api.yaml:/usr/share/nginx/html/api.yaml
